### ISSUE TITLE
Spike Weekend - 2017-02-11

### ISSUE THREAD

**Issue by jeschkies** [turner-renderer/turner#91]
I'd just call our meetings on the weekend "Spike Weekends" as in spike stories.

This is our agenda:

- [x] Overhaul Readme.
- [ ] Document Hierarchical Radiosity.
- [x] Render images for regression testing for each PR.
- [x] Merge remaining PR
- [x] Add output operator of Config classes #89

**Comment by boxdot** [comment]
Nice.
